### PR TITLE
Add ccordoba12 and andfoy as maintainers of this package

### PR DESCRIPTION
**Pull request by andfoy**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by andfoy** [comment]
@conda-forge-admin, please rerender

**Comment by andfoy** [comment]
@conda-forge/core Is it possible to merge this one?

**Comment by isuruf** [comment]
@andfoy, see https://github.com/conda-forge/textdistance-feedstock/pull/10#issuecomment-720804333. Github handle is wrong.

**Comment by andfoy** [comment]
@isuruf, I don't know what's happening with the linter, but @ccordoba12 does exist

**Comment by andfoy** [comment]
@isuruf, that was a minor typo indeed, it should be fixed now

**Comment by isuruf** [comment]
@ccordoba12, can you confirm that you want to be a maintainer?

**Comment by ccordoba12** [comment]
Yep, I confirm I want to be a maintainer of this package.

**Comment by synapticarbors** [comment]
I just fixed the license type on this since it's MIT not LGPL.

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@isuruf, @synapticarbors, I think this one is ready. Could you merge it?

**Pull request merged**
